name: CI

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/setup-node@v2.3.0
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: "npm install"
      
      - name: Build
        run: npm run build

      - name: Publish new version if updated
        uses: pascalgn/npm-publish-action@1.3.8
        with: 
          publish_command: "yarn"
          publish_args: "--access public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
